import crypto from 'node:crypto';
import { Router, Request, Response, NextFunction } from 'express';
import { z } from 'zod';
import { getDatabase } from './database.js';

type Session = { id: string; role?: string; sid?: string };
type SessionReader = (request: Request) => Session | null;
const roles: Record<string, string[]> = {
  admin: ['*'], gestor: ['demands:read','demands:create','demands:update','demands:delete','clients:read','clients:create','clients:update','teams:read','teams:create','teams:update'],
  diretoria: ['demands:read','clients:read','teams:read','audit:read'], colaborador: ['demands:read','demands:create','demands:update','clients:read','teams:read']
};
export const hasRolePermission = (role: string, permission: string) => Boolean(roles[role]?.includes('*') || roles[role]?.includes(permission));

export const createApiRouter = (readSession: SessionReader) => {
  const router = Router();
  const authenticated = (req: Request, res: Response, next: NextFunction) => { const session = readSession(req); if (!session) return res.status(401).json({ message: 'Sessão inválida.' }); res.locals.session = session; next(); };
  const authorize = (permission: string) => (req: Request, res: Response, next: NextFunction) => { const session = res.locals.session as Session; if (!hasRolePermission(session.role || 'colaborador', permission)) return res.status(403).json({ message: 'Permissão insuficiente.' }); next(); };
  const audit = async (req: Request, action: string, entityType: string, entityId: string | null, before: unknown, after: unknown) => { const session = readSession(req)!; await getDatabase().insertInto('audit_logs').values({ id:crypto.randomUUID(), actor_id: session.id, session_id: session.sid || null, ip_address: req.ip || null, action, entity_type: entityType, entity_id: entityId, before_data: before ?? null, after_data: after ?? null, created_at:new Date() }).execute(); };
  const safe = (handler: (req: Request, res: Response) => Promise<unknown>) => async (req: Request, res: Response) => { try { await handler(req,res); } catch (error) { console.error(error); res.status(500).json({ message: 'Falha interna ao processar a operação.' }); } };

  router.use(authenticated);
  router.get('/bootstrap', safe(async (_req,res) => { const db=getDatabase(); const [users,teams,members,clients,demands,configurations,audits]=await Promise.all([db.selectFrom('users').selectAll().execute(),db.selectFrom('teams').selectAll().execute(),db.selectFrom('team_members').selectAll().execute(),db.selectFrom('clients').selectAll().execute(),db.selectFrom('demands').selectAll().execute(),db.selectFrom('configurations').selectAll().execute(),db.selectFrom('audit_logs').selectAll().orderBy('created_at','desc').limit(200).execute()]); res.json({currentUserId:(res.locals.session as Session).id,users:users.map(user=>({id:user.id,email:user.email,name:user.name,role:user.role,roleTitle:user.role_title,department:user.department,branch:user.branch,phone:user.phone,avatar:user.avatar||'',active:user.active,approvalStatus:'approved',teamIds:members.filter(m=>m.user_id===user.id).map(m=>m.team_id)})),teams:teams.map(team=>({id:team.id,name:team.name,description:team.description,department:team.department,leaderId:team.leader_id||'',color:team.color,active:team.active,memberIds:members.filter(m=>m.team_id===team.id).map(m=>m.user_id)})),clients,demands:demands.map(row=>({...row,...(row.payload as object)})),auditLogs:audits,configurations:Object.fromEntries(configurations.map(item=>[item.key,item.value]))}); }));

  const clientSchema=z.object({name:z.string().min(2).max(160),company:z.string().min(2).max(160),email:z.string().email(),phone:z.string().max(40).optional().default(''),active:z.boolean().optional().default(true)});
  router.get('/clients',authorize('clients:read'),safe(async(_req,res)=>res.json(await getDatabase().selectFrom('clients').selectAll().orderBy('company').execute())));
  router.post('/clients',authorize('clients:create'),safe(async(req,res)=>{const input=clientSchema.parse(req.body);const now=new Date();const record={id:`cli-${crypto.randomUUID()}`,...input,created_at:now,updated_at:now};await getDatabase().insertInto('clients').values(record).execute();await audit(req,'CREATE','client',record.id,null,record);res.status(201).json(record);}));
  router.patch('/clients/:id',authorize('clients:update'),safe(async(req,res)=>{const input=clientSchema.partial().parse(req.body);const before=await getDatabase().selectFrom('clients').selectAll().where('id','=',req.params.id).executeTakeFirst();if(!before)return res.status(404).json({message:'Cliente não encontrado.'});await getDatabase().updateTable('clients').set({...input,updated_at:new Date()}).where('id','=',req.params.id).execute();await audit(req,'UPDATE','client',req.params.id,before,input);res.json({...before,...input});}));

  const teamSchema=z.object({name:z.string().min(2).max(120),description:z.string().max(500).default(''),department:z.string().max(120).default(''),leaderId:z.string().nullable().optional(),color:z.string().regex(/^#[0-9a-f]{6}$/i).default('#2563eb'),active:z.boolean().default(true),memberIds:z.array(z.string()).default([])});
  router.get('/teams',authorize('teams:read'),safe(async(_req,res)=>res.json(await getDatabase().selectFrom('teams').selectAll().orderBy('name').execute())));
  router.post('/teams',authorize('teams:create'),safe(async(req,res)=>{const input=teamSchema.parse(req.body);const id=`team-${crypto.randomUUID()}`;const now=new Date();await getDatabase().transaction().execute(async trx=>{await trx.insertInto('teams').values({id,name:input.name,description:input.description,department:input.department,leader_id:input.leaderId||null,color:input.color,active:input.active,created_at:now,updated_at:now}).execute();if(input.memberIds.length)await trx.insertInto('team_members').values(input.memberIds.map(user_id=>({team_id:id,user_id,created_at:now}))).execute();});await audit(req,'CREATE','team',id,null,input);res.status(201).json({id,...input});}));
  router.patch('/teams/:id',authorize('teams:update'),safe(async(req,res)=>{const input=teamSchema.partial().parse(req.body);const db=getDatabase();const before=await db.selectFrom('teams').selectAll().where('id','=',req.params.id).executeTakeFirst();if(!before)return res.status(404).json({message:'Equipe não encontrada.'});await db.transaction().execute(async trx=>{await trx.updateTable('teams').set({name:input.name??before.name,description:input.description??before.description,department:input.department??before.department,leader_id:input.leaderId===undefined?before.leader_id:input.leaderId,color:input.color??before.color,active:input.active??before.active,updated_at:new Date()}).where('id','=',req.params.id).execute();if(input.memberIds){await trx.deleteFrom('team_members').where('team_id','=',req.params.id).execute();if(input.memberIds.length)await trx.insertInto('team_members').values(input.memberIds.map(user_id=>({team_id:req.params.id,user_id,created_at:new Date()}))).execute();}});await audit(req,'UPDATE','team',req.params.id,before,input);res.json({...before,...input});}));
  router.delete('/teams/:id',authorize('teams:update'),safe(async(req,res)=>{const db=getDatabase();const before=await db.selectFrom('teams').selectAll().where('id','=',req.params.id).executeTakeFirst();if(!before)return res.status(404).json({message:'Equipe não encontrada.'});await db.deleteFrom('teams').where('id','=',req.params.id).execute();await audit(req,'DELETE','team',req.params.id,before,null);res.status(204).end();}));

  const demandSchema=z.object({id:z.string().optional(),code:z.string().min(1).max(40),title:z.string().min(2).max(240),description:z.string().max(10000).default(''),statusId:z.string(),priorityId:z.string(),categoryId:z.string(),requesterId:z.string().optional(),assigneeId:z.string().nullable().optional(),teamId:z.string().nullable().optional(),clientId:z.string().nullable().optional(),dueDate:z.string().datetime().nullable().optional()}).passthrough();
  router.get('/demands',authorize('demands:read'),safe(async(_req,res)=>{const rows=await getDatabase().selectFrom('demands').selectAll().orderBy('updated_at','desc').execute();res.json(rows.map(row=>({...row,...(row.payload as object)})));}));
  router.post('/demands',authorize('demands:create'),safe(async(req,res)=>{const input=demandSchema.parse(req.body);const session=res.locals.session as Session;const id=input.id||`dem-${crypto.randomUUID()}`;const record={...input,id,requesterId:session.id};const now=new Date();await getDatabase().insertInto('demands').values({id,code:input.code,title:input.title,description:input.description,status_id:input.statusId,priority_id:input.priorityId,category_id:input.categoryId,requester_id:session.id,assignee_id:input.assigneeId||null,team_id:input.teamId||null,client_id:input.clientId||null,due_date:input.dueDate?new Date(input.dueDate):null,payload:record,version:1,created_at:now,updated_at:now}).execute();await audit(req,'CREATE','demand',id,null,record);res.status(201).json(record);}));
  router.patch('/demands/:id',authorize('demands:update'),safe(async(req,res)=>{const input=demandSchema.partial().parse(req.body);const db=getDatabase();const before=await db.selectFrom('demands').selectAll().where('id','=',req.params.id).executeTakeFirst();if(!before)return res.status(404).json({message:'Demanda não encontrada.'});const payload={...(before.payload as object),...input};await db.updateTable('demands').set({title:input.title??before.title,description:input.description??before.description,status_id:input.statusId??before.status_id,priority_id:input.priorityId??before.priority_id,category_id:input.categoryId??before.category_id,assignee_id:input.assigneeId===undefined?before.assignee_id:input.assigneeId,team_id:input.teamId===undefined?before.team_id:input.teamId,client_id:input.clientId===undefined?before.client_id:input.clientId,due_date:input.dueDate===undefined?before.due_date:input.dueDate?new Date(input.dueDate):null,payload,version:before.version+1,updated_at:new Date()}).where('id','=',req.params.id).execute();await audit(req,'UPDATE','demand',req.params.id,before,input);res.json(payload);}));
  router.delete('/demands/:id',authorize('demands:delete'),safe(async(req,res)=>{const db=getDatabase();const before=await db.selectFrom('demands').selectAll().where('id','=',req.params.id).executeTakeFirst();if(!before)return res.status(404).json({message:'Demanda não encontrada.'});await db.deleteFrom('demands').where('id','=',req.params.id).execute();await audit(req,'DELETE','demand',req.params.id,before,null);res.status(204).end();}));

  router.get('/audit-logs',authorize('audit:read'),safe(async(req,res)=>{const limit=Math.min(Number(req.query.limit)||100,500);res.json(await getDatabase().selectFrom('audit_logs').selectAll().orderBy('created_at','desc').limit(limit).execute());}));
  return router;
};
