import crypto from "node:crypto";
import path from "node:path";
import { mkdir, rm, writeFile } from "node:fs/promises";
import request from "supertest";
import { afterAll, beforeAll, describe, expect, it } from "vitest";
import { createApp } from "./app.js";
import { closeDatabase, getDatabase } from "./database.js";
import { hashPassword } from "./password.js";

const run=process.env.RUN_DB_TESTS==="true";
const suffix=crypto.randomUUID();
const ownerId=`attachment-owner-${suffix}`;
const outsiderId=`attachment-outsider-${suffix}`;
const moduleId=`attachment-module-${suffix}`;
const otherModuleId=`attachment-other-${suffix}`;
const demandId=`attachment-demand-${suffix}`;
const commentId=`attachment-comment-${suffix}`;
const key=`${crypto.randomUUID()}.png`;
const bytes=Buffer.from("iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=","base64");
const uploadDir=path.resolve(process.env.UPLOAD_DIR||".test-uploads");
const csrf=async(agent:ReturnType<typeof request.agent>)=>{const response=await agent.get("/api/auth/config").expect(200);const raw=String(response.headers["set-cookie"]?.[0]??response.headers["set-cookie"]??"");return decodeURIComponent(raw.match(/prolog_csrf=([^;]+)/)?.[1]??"");};

describe.skipIf(!run)("download protegido de anexos",()=>{
  let app:Awaited<ReturnType<typeof createApp>>;
  beforeAll(async()=>{const db=getDatabase();const now=new Date();const security={deleted_at:null,password_changed_at:null,mfa_enabled:false,mfa_secret_encrypted:null,failed_mfa_attempts:0,locked_until:null};await mkdir(uploadDir,{recursive:true});await writeFile(path.join(uploadDir,key),bytes,{flag:"wx"});await db.insertInto("users").values([{id:ownerId,email:`${ownerId}@test.local`,name:"Owner",password_hash:hashPassword("Owner123"),role:"colaborador",role_title:"Analista",department:"Teste",branch:null,phone:null,avatar:null,active:true,force_password_change:false,...security,created_at:now,updated_at:now},{id:outsiderId,email:`${outsiderId}@test.local`,name:"Outsider",password_hash:hashPassword("Outsider123"),role:"colaborador",role_title:"Analista",department:"Teste",branch:null,phone:null,avatar:null,active:true,force_password_change:false,...security,created_at:now,updated_at:now}]).execute();await db.insertInto("operational_modules").values([{id:moduleId,name:"Anexos",slug:`anexos-${suffix}`,description:"",icon_key:"Briefcase",color:"#2563eb",active:true,created_by:ownerId,version:1,deleted_at:null,created_at:now,updated_at:now},{id:otherModuleId,name:"Outro",slug:`outro-${suffix}`,description:"",icon_key:"Briefcase",color:"#2563eb",active:true,created_by:ownerId,version:1,deleted_at:null,created_at:now,updated_at:now}]).execute();await db.insertInto("module_members").values([{module_id:moduleId,user_id:ownerId,role:"member",active:true,created_by:ownerId,created_at:now,updated_at:now},{module_id:otherModuleId,user_id:outsiderId,role:"member",active:true,created_by:ownerId,created_at:now,updated_at:now}]).execute();const attachment={id:`att-${suffix}`,name:"pixel.png",size:bytes.length,type:"image/png",url:`/uploads/${key}`,uploadedByUserId:ownerId,uploadedAt:now.toISOString()};await db.insertInto("demands").values({id:demandId,module_id:moduleId,code:`ATT-${suffix.slice(0,6)}`,title:"Anexo protegido",description:"",status_id:"nova",priority_id:"normal",category_id:"tarefa",requester_id:ownerId,assignee_id:null,team_id:null,client_id:null,sprint_id:null,backlog_position:0,due_date:null,payload:{comments:[{id:commentId,userId:ownerId,userName:"Owner",userAvatar:"",content:"Arquivo",createdAt:now.toISOString(),attachments:[attachment]}]},version:1,deleted_at:null,completed_at:null,archived_at:null,created_at:now,updated_at:now}).execute();await db.insertInto("attachment_files").values({id:`attf-${suffix}`,demand_id:demandId,comment_id:commentId,storage_key:key,original_name:"pixel.png",mime_type:"image/png",size_bytes:bytes.length,uploaded_by:ownerId,created_at:now}).execute();app=await createApp();});
  afterAll(async()=>{const db=getDatabase();await db.deleteFrom("user_permissions").where("user_id","in",[ownerId,outsiderId]).execute();await db.deleteFrom("auth_sessions").where("user_id","in",[ownerId,outsiderId]).execute();await db.deleteFrom("attachment_files").where("demand_id","=",demandId).execute();await db.deleteFrom("demands").where("id","=",demandId).execute();await db.deleteFrom("module_members").where("module_id","in",[moduleId,otherModuleId]).execute();await db.deleteFrom("operational_modules").where("id","in",[moduleId,otherModuleId]).execute();await db.deleteFrom("users").where("id","in",[ownerId,outsiderId]).execute();await rm(path.join(uploadDir,key),{force:true});await closeDatabase();});
  it("autoriza por recurso, nega enumeração e atualiza acesso na mesma sessão",async()=>{const db=getDatabase();await request(app).get(`/uploads/${key}`).expect(401);const owner=request.agent(app);const token=await csrf(owner);await owner.post("/api/auth/login").set("X-CSRF-Token",token).send({email:`${ownerId}@test.local`,password:"Owner123"}).expect(200);const get=await owner.get(`/uploads/${key}`).expect(200);expect(get.headers["content-type"]).toMatch(/^image\/png/);expect(get.headers["cache-control"]).toBe("private, no-store");expect(get.headers["x-content-type-options"]).toBe("nosniff");expect(Buffer.from(get.body)).toEqual(bytes);const head=await owner.head(`/uploads/${key}`).expect(200);expect(head.text).toBeUndefined();const outsider=request.agent(app);const outsiderToken=await csrf(outsider);await outsider.post("/api/auth/login").set("X-CSRF-Token",outsiderToken).send({email:`${outsiderId}@test.local`,password:"Outsider123"}).expect(200);const denied=await outsider.get(`/uploads/${key}`).expect(404);expect(denied.body).not.toEqual(bytes);await owner.get(`/uploads/${crypto.randomUUID()}.png`).expect(404);await owner.get(`/uploads/${crypto.randomUUID()}.png`).expect(404);await db.updateTable("module_members").set({active:false,updated_at:new Date()}).where("module_id","=",moduleId).where("user_id","=",ownerId).execute();await owner.get(`/uploads/${key}`).expect(404);await db.updateTable("module_members").set({active:true,updated_at:new Date()}).where("module_id","=",moduleId).where("user_id","=",ownerId).execute();await db.insertInto("user_permissions").values({user_id:ownerId,permission:"demands:read",effect:"deny",created_by:ownerId,created_at:new Date()}).execute();await owner.get(`/uploads/${key}`).expect(404);await db.deleteFrom("user_permissions").where("user_id","=",ownerId).execute();await db.updateTable("demands").set({deleted_at:new Date()}).where("id","=",demandId).execute();await owner.get(`/uploads/${key}`).expect(404);await db.updateTable("demands").set({deleted_at:null}).where("id","=",demandId).execute();await rm(path.join(uploadDir,key),{force:true});await owner.get(`/uploads/${key}`).expect(404);await writeFile(path.join(uploadDir,key),bytes,{flag:"wx"});await owner.get("/uploads/%2e%2e%2fsecret.png").expect(404);});
  it("falha fechada quando a autorização está indisponível",async()=>{const failing=await createApp({authorizationOverrideReader:async()=>{throw new Error("unavailable");}});const agent=request.agent(failing);const token=await csrf(agent);await agent.post("/api/auth/login").set("X-CSRF-Token",token).send({email:`${ownerId}@test.local`,password:"Owner123"}).expect(200);const response=await agent.get(`/uploads/${key}`).expect(503);expect(response.body).not.toEqual(bytes);});
});
