import crypto from "node:crypto";
import { afterAll, beforeAll, describe, expect, it } from "vitest";
import { backfillAttachmentMetadata } from "./attachments/backfill.js";
import { closeDatabase, getDatabase } from "./database.js";
import { hashPassword } from "./password.js";
const run=process.env.RUN_DB_TESTS==="true";const suffix=crypto.randomUUID();const userId=`backfill-user-${suffix}`;const moduleId=`backfill-module-${suffix}`;const demandId=`backfill-demand-${suffix}`;const key=`${crypto.randomUUID()}.png`;const ambiguousKey=`${crypto.randomUUID()}.png`;
const attachment=(storageKey:string,id:string)=>({id,name:"legacy.png",size:68,type:"image/png",url:`/uploads/${storageKey}`,uploadedByUserId:userId,uploadedAt:new Date().toISOString()});
describe.skipIf(!run)("backfill de anexos legados",()=>{
beforeAll(async()=>{const db=getDatabase();const now=new Date();await db.insertInto("users").values({id:userId,email:`${userId}@test.local`,name:"Backfill",password_hash:hashPassword("Backfill123"),role:"colaborador",role_title:"Analista",department:"Teste",branch:null,phone:null,avatar:null,active:true,force_password_change:false,deleted_at:null,password_changed_at:null,mfa_enabled:false,mfa_secret_encrypted:null,failed_mfa_attempts:0,locked_until:null,created_at:now,updated_at:now}).execute();await db.insertInto("operational_modules").values({id:moduleId,name:"Backfill",slug:`backfill-${suffix}`,description:"",icon_key:"Briefcase",color:"#2563eb",active:true,created_by:userId,version:1,deleted_at:null,created_at:now,updated_at:now}).execute();await db.insertInto("demands").values({id:demandId,module_id:moduleId,code:`BF-${suffix.slice(0,6)}`,title:"Legado",description:"",status_id:"nova",priority_id:"normal",category_id:"tarefa",requester_id:userId,assignee_id:null,team_id:null,client_id:null,sprint_id:null,backlog_position:0,due_date:null,payload:{comments:[{id:"unique-comment",attachments:[attachment(key,"unique")]},{id:"ambiguous-one",attachments:[attachment(ambiguousKey,"amb-1")]},{id:"ambiguous-two",attachments:[attachment(ambiguousKey,"amb-2")]}]},version:1,deleted_at:null,completed_at:null,archived_at:null,created_at:now,updated_at:now}).execute();});
afterAll(async()=>{const db=getDatabase();await db.deleteFrom("attachment_backfill_issues").where("storage_key","=",ambiguousKey).execute();await db.deleteFrom("attachment_files").where("demand_id","=",demandId).execute();await db.deleteFrom("demands").where("id","=",demandId).execute();await db.deleteFrom("operational_modules").where("id","=",moduleId).execute();await db.deleteFrom("users").where("id","=",userId).execute();await closeDatabase();});
it("é idempotente e não atribui referência ambígua",async()=>{const db=getDatabase();await backfillAttachmentMetadata(db);await backfillAttachmentMetadata(db);const records=await db.selectFrom("attachment_files").select("storage_key").where("demand_id","=",demandId).execute();expect(records).toEqual([{storage_key:key}]);expect(await db.selectFrom("attachment_backfill_issues").select("reference_count").where("storage_key","=",ambiguousKey).executeTakeFirst()).toEqual({reference_count:2});});
});
