import React, { useMemo } from 'react';
import { AlertTriangle, Ban, CalendarClock, CheckCircle2, ClipboardList, Clock3, Info, Target, TrendingUp } from 'lucide-react';
import { Bar, CartesianGrid, ComposedChart, Line, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { CategoryConfig, Demand, StatusConfig } from '../../types';
import { formatCalendarDate, isCalendarDateOverdue } from '../../utils/date';
import { AnimatedNumber } from '../common/AnimatedNumber';
import { ReportConfiguration } from './reportBuilder';
import { calculateExecutiveMetrics, daysLate, projectionLevel } from './reportCalculations';

type Props={id?:string;demands:Demand[];categories:CategoryConfig[];statuses:StatusConfig[];clientFilterText:string;teamFilterText:string;periodText:string;periodStart?:Date|null;configuration:ReportConfiguration;onConfigure?:()=>void};
const levelStyle={on_track:{label:'No caminho',color:'text-emerald-600',border:'border-emerald-500',bg:'bg-emerald-50'},attention:{label:'Em atenção',color:'text-amber-600',border:'border-amber-500',bg:'bg-amber-50'},high_risk:{label:'Alto risco',color:'text-orange-600',border:'border-orange-600',bg:'bg-orange-50'},critical:{label:'Crítico',color:'text-red-600',border:'border-red-500',bg:'bg-red-50'}};
const Card:React.FC<{children:React.ReactNode;className?:string}>=({children,className=''})=><div className={`rounded-2xl border border-[#DCE3ED] bg-white p-5 shadow-sm dark:border-slate-700 dark:bg-slate-900 ${className}`}>{children}</div>;
const Section=({n,title}:{n:string;title:string})=><div className="mb-3 mt-6 flex items-center gap-3"><span className="grid h-6 min-w-7 place-items-center rounded-md bg-blue-50 px-1.5 font-mono text-[11px] font-black text-blue-600 dark:bg-blue-950">{n}</span><h2 className="text-[15px] font-black uppercase tracking-wide text-[#172033] dark:text-slate-100">{title}</h2><i className="h-px flex-1 bg-[#DCE3ED] dark:bg-slate-700"/></div>;
const statusOfDue=(item:{dueDate:string},now:Date)=>{if(!isCalendarDateOverdue(item.dueDate,now))return 'No prazo';const days=daysLate(item.dueDate,now);return days===0?'Vencida hoje':`Vencida há ${days} ${days===1?'dia':'dias'}`;};

export const ExecutiveOverviewReportV2:React.FC<Props>=({id,demands,statuses,clientFilterText,teamFilterText,periodText,periodStart,configuration})=>{
 const now=new Date(),reference=periodStart||now,quarter=Math.floor(reference.getMonth()/3)+1,year=reference.getFullYear();
 const metrics=useMemo(()=>calculateExecutiveMetrics(demands,statuses,now,quarter,year),[demands,statuses,now.toDateString(),quarter,year]);
 const level=levelStyle[projectionLevel(metrics.projectionRate)];const showPortfolio=demands.length!==metrics.commitment;
 const kpis=[...(showPortfolio?[{icon:ClipboardList,label:'Carteira total',value:demands.length,tone:'text-blue-600 bg-blue-50'}]:[]),{icon:Target,label:'Compromisso trimestral',value:metrics.commitment,tone:'text-blue-600 bg-blue-50'},{icon:CheckCircle2,label:'Entregues no trimestre',value:metrics.completed.length,tone:'text-emerald-600 bg-emerald-50'},{icon:TrendingUp,label:'Realizado até agora',value:metrics.actualRate,suffix:'%',tone:'text-blue-600 bg-blue-50'},{icon:Clock3,label:'Vencidas',value:metrics.overdue.length,tone:'text-red-600 bg-red-50'},{icon:Ban,label:'Impedidas',value:metrics.blocked.length,tone:'text-orange-600 bg-orange-50'}];
 const risks=[...(configuration.riskItems||[])].sort((a,b)=>({critical:0,high:1,medium:2,low:3}[a.severity]-{critical:0,high:1,medium:2,low:3}[b.severity])||String(a.resolutionDueDate||'9999').localeCompare(String(b.resolutionDueDate||'9999')));
 const demandMap=new Map<string,Demand>(demands.map(item=>[item.id,item]));
 const autoImpacts=metrics.completed.slice(0,4).map(item=>({id:item.id,sourceDemandId:item.id,title:item.title,outcome:item.expectedOutcome||'Benefício ainda não informado.',order:0}));const impacts=(configuration.impactItems||[]).length?[...configuration.impactItems].sort((a,b)=>a.order-b.order):autoImpacts;
 const autoMilestones=metrics.active.sort((a,b)=>a.dueDate.localeCompare(b.dueDate)).slice(0,4).map(item=>({id:item.id,sourceDemandId:item.id,title:item.title,dueDate:item.dueDate,progress:item.progressPercent,risk:isCalendarDateOverdue(item.dueDate)?'high' as const:item.blocker?.isBlocked?'medium' as const:'low' as const,order:0}));const milestones=(configuration.milestoneItems||[]).length?[...configuration.milestoneItems].sort((a,b)=>a.order-b.order):autoMilestones;
 const gapText=metrics.surplus?`Meta superada em ${metrics.surplus} entregas`:`${metrics.gap} entregas abaixo do compromisso trimestral`;
 return <div id={id} className="report-executive-v2 w-full rounded-2xl bg-[#F4F7FB] p-6 text-[#172033] dark:bg-slate-950 dark:text-slate-100 print:p-4">
  <header className="rounded-2xl bg-[#14213D] px-6 py-5 text-white shadow-md"><div className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div><p className="text-[11px] font-bold uppercase tracking-[.2em] text-blue-300">Relatório executivo</p><h1 className="mt-1 text-[30px] font-black">Demandas — {quarter}º Trimestre</h1><div className="mt-2 space-y-1 text-[13px] text-slate-300"><p>Cliente solicitante: <b className="text-white">{clientFilterText}</b></p><p>Equipe responsável: <b className="text-white">{teamFilterText}</b></p>{!showPortfolio&&<p>Carteira total: <b className="text-white">{demands.length} demandas</b></p>}</div></div><div className="rounded-xl border border-white/15 bg-white/5 px-4 py-3 text-[13px]"><p className="flex items-center gap-2 font-bold"><CalendarClock className="h-4 w-4 text-blue-300"/>{periodText}</p><p className="mt-1 text-[12px] text-slate-400">Atualizado em {now.toLocaleDateString('pt-BR')}</p></div></div></header>
  <Section n="01" title="Indicadores"/><div className={`grid gap-4 ${kpis.length===5?'xl:grid-cols-5':'xl:grid-cols-6'} sm:grid-cols-2 lg:grid-cols-3`}>{kpis.map(({icon:Icon,...item})=><Card key={item.label} className="min-h-36 border-t-4 border-t-current"><span className={`grid h-10 w-10 place-items-center rounded-xl ${item.tone}`}><Icon className="h-5 w-5"/></span><AnimatedNumber value={item.value} suffix={item.suffix} className="mt-4 block text-[34px] font-black leading-none"/><p className="mt-2 text-[13px] font-semibold text-slate-600 dark:text-slate-300">{item.label}</p></Card>)}</div>
  <Section n="02" title="Leitura executiva"/><div className="grid gap-4 lg:grid-cols-3"><StatusCard title="Situação atual" value={`${metrics.completed.length} de ${metrics.commitment}`} indicator={`${metrics.actualRate}% realizado`} detail={`${metrics.overdue.length} vencidas e ${metrics.blocked.length} impedidas.`} tone="blue"/><StatusCard title="Projeção de fechamento" value={metrics.projectionAvailable?`${metrics.projected} de ${metrics.commitment}`:'Dado indisponível'} indicator={metrics.projectionAvailable?`${metrics.projectionRate}% projetado`:'Histórico insuficiente'} detail="Projeção calculada pelo ritmo atual do trimestre." tone={level.color} badge={level.label} border={level.border} bg={level.bg}/><StatusCard title="Gap projetado" value={metrics.projectionAvailable?String(metrics.gap):'—'} indicator={metrics.projectionAvailable?gapText:'Histórico insuficiente para projeção'} detail={metrics.gap?'Risco de não atingimento do compromisso.':'Compromisso projetado como atingido.'} tone={metrics.gap?'text-red-600':'text-emerald-600'} border={metrics.gap?'border-red-500':'border-emerald-500'} bg={metrics.gap?'bg-red-50':'bg-emerald-50'}/></div>
  <Card className="mt-4 border-l-4 border-l-blue-500"><h3 className="text-[14px] font-black">Insight executivo</h3><p className="mt-2 text-[14px] leading-6 text-slate-600 dark:text-slate-300">O trimestre atingiu {metrics.actualRate}% do compromisso. {metrics.projectionAvailable?`Mantido o ritmo atual, deverá encerrar com ${metrics.projected} das ${metrics.commitment} entregas previstas, gerando ${gapText.toLowerCase()}.`:'Não há histórico suficiente para projeção.'} {metrics.overdue.length} demandas estão vencidas e {metrics.blocked.length} impedidas. Não há informações suficientes para determinar a principal causa do desvio. Este período estabelece a linha de base para as comparações dos próximos ciclos.</p></Card>
  <Section n="03" title="Evolução e saúde"/><div className="grid items-start gap-4 xl:grid-cols-2"><Card><h3 className="text-[14px] font-black">Evolução do trimestre</h3><div className="mt-3 h-56"><ResponsiveContainer><ComposedChart data={metrics.months}><CartesianGrid vertical={false} stroke="#64748B" strokeOpacity={.28}/><XAxis dataKey="mes" tick={{fontSize:12,fill:'#64748B'}}/><YAxis tick={{fontSize:12,fill:'#64748B'}} width={32}/><Tooltip/><Bar dataKey="planejado" name="Planejado/mês" fill="#93C5FD"/><Bar dataKey="realizado" name="Realizado/mês" fill="#10B981"/><Line dataKey="planejadoAcumulado" name="Planejado acumulado" stroke="#14213D" strokeWidth={2}/><Line dataKey="realizadoAcumulado" name="Realizado acumulado" stroke="#10B981" strokeWidth={2.5}/><Line dataKey="projecao" name="Projeção" stroke="#EA580C" strokeDasharray="6 4" strokeWidth={2}/></ComposedChart></ResponsiveContainer></div><div className="mt-2 grid grid-cols-4 gap-2 text-center text-[12px]"><small>Meta: <b>{metrics.commitment}</b></small><small>Realizado: <b>{metrics.completed.length}</b></small><small>Projetado: <b>{metrics.projected}</b></small><small>Gap: <b>{metrics.gap}</b></small></div></Card><Card><div className="flex items-center justify-between"><h3 className="text-[14px] font-black">Saúde do portfólio</h3><span title={`${metrics.onTimeNumerator} de ${metrics.onTimeDenominator} demandas ativas com prazo não estão vencidas em ${now.toLocaleDateString('pt-BR')}`}><Info className="h-4 w-4 text-slate-400"/></span></div><div className="mt-4 grid grid-cols-2 gap-3"><Health label="Dentro do prazo" value={metrics.onTimeRate===null?'—':`${metrics.onTimeRate}%`} tone="green"/><Health label="Vencidas" value={metrics.overdue.length} tone="red"/><Health label="Impedidas" value={metrics.blocked.length} tone="orange"/><Health label="Entregas por mês" value={metrics.monthlyPace} tone="blue"/></div><p className="mt-3 text-[12px] text-slate-500">Dentro do prazo: {metrics.onTimeNumerator} de {metrics.onTimeDenominator} demandas ativas com prazo, na data de emissão.</p></Card></div>
  {configuration.showRisksAndDecisions&&<><Section n="04" title="Riscos e decisões"/><Card className="overflow-x-auto"><table className="w-full min-w-[900px] text-left text-[12px]"><thead><tr className="bg-slate-50 dark:bg-slate-800">{['Demanda','Risco ou impedimento','Impacto','Responsável','Prazo','Decisão necessária'].map(x=><th key={x} className="p-3">{x}</th>)}</tr></thead><tbody>{risks.map(item=><tr key={item.id} className="border-t"><td className="p-3 font-bold">{item.demandName}</td><td className="p-3">{item.risk}</td><td className="p-3">{item.impact}</td><td className="p-3">{item.responsible}</td><td className="p-3">{item.resolutionDueDate?formatCalendarDate(item.resolutionDueDate):'A definir'}</td><td className="p-3">{item.decision}</td></tr>)}</tbody></table></Card></>}
  <Section n={configuration.showRisksAndDecisions?'05':'04'} title="Entregas e marcos"/><div className="grid items-start gap-4 lg:grid-cols-2">{configuration.showImpactDeliveries!==false&&<Card><h3 className="mb-3 text-[14px] font-black">Entregas de maior impacto</h3><div className="space-y-3">{impacts.map(item=>{const source=item.sourceDemandId?demandMap.get(item.sourceDemandId):undefined;return <div key={item.id} className="rounded-xl border bg-slate-50 p-3 dark:bg-slate-800"><b className="text-[14px]">{item.title}</b><p className="mt-1 text-[13px] text-slate-600 dark:text-slate-300">{item.outcome||'Benefício ainda não informado.'}</p>{source?.completedAt&&<small className="mt-1 block text-[12px] text-slate-500">Concluída em {new Date(source.completedAt).toLocaleDateString('pt-BR')}</small>}</div>})}</div></Card>}{configuration.showMilestones!==false&&<Card><h3 className="mb-3 text-[14px] font-black">Marcos críticos</h3><div className="space-y-3">{milestones.map(item=>{const source=item.sourceDemandId?demandMap.get(item.sourceDemandId):undefined;const due=statusOfDue(item,now);return <div key={item.id} className="rounded-xl border p-3"><div className="flex justify-between gap-2"><b className="text-[14px]">{item.title}</b><span className="text-[12px] font-bold text-red-600">{item.risk==='high'?'Risco alto':item.risk==='medium'?'Risco médio':'Risco baixo'}</span></div><div className="mt-1 flex flex-wrap gap-2 text-[12px] text-slate-500"><span>Prazo {formatCalendarDate(item.dueDate)}</span><b className={due==='No prazo'?'text-emerald-600':'text-red-600'}>{due}</b>{source?.blocker?.isBlocked&&<b className="text-orange-600">Impedida</b>}</div><div className="mt-2 h-2 rounded-full bg-slate-200"><div className="h-full rounded-full bg-blue-500" style={{width:`${item.progress}%`}}/></div><p className="mt-1 text-right text-[12px] font-bold">{item.progress}%</p></div>})}</div></Card>}</div>
  <footer className="mt-6 border-t pt-3 text-[11px] text-slate-500">Trimestre de referência inicial · Fonte: Sistema de Gestão de Demandas · Atualizado em {now.toLocaleDateString('pt-BR')}</footer>
 </div>;
};
const StatusCard=({title,value,indicator,detail,tone='text-blue-600',badge,border='border-blue-500',bg='bg-blue-50'}:{title:string;value:string;indicator:string;detail:string;tone?:string;badge?:string;border?:string;bg?:string})=><Card className={`min-h-48 border-t-4 ${border}`}><div className="flex justify-between"><h3 className="text-[14px] font-black">{title}</h3>{badge&&<span className={`rounded-full px-2 py-1 text-[11px] font-bold ${tone} ${bg}`}>{badge}</span>}</div><p className={`mt-4 text-[30px] font-black ${tone}`}>{value}</p><p className="mt-1 text-[14px] font-bold">{indicator}</p><p className="mt-3 text-[13px] text-slate-500">{detail}</p></Card>;
const Health=({label,value,tone}:{label:string;value:string|number;tone:'green'|'red'|'orange'|'blue'})=>{const color={green:'border-emerald-200 bg-emerald-50 text-emerald-700',red:'border-red-200 bg-red-50 text-red-700',orange:'border-orange-200 bg-orange-50 text-orange-700',blue:'border-blue-200 bg-blue-50 text-blue-700'}[tone];return <div className={`rounded-xl border p-4 ${color}`}><b className="block text-[26px] font-black">{value}</b><span className="text-[12px] font-semibold">{label}</span></div>};
