import React, { useMemo } from 'react';
import { motion, useReducedMotion } from 'framer-motion';
import { AlertTriangle, ArrowUpRight, Ban, CalendarClock, CheckCircle2, ChevronRight, ClipboardList, Clock3, RefreshCw, ShieldCheck, Target, TrendingUp } from 'lucide-react';
import { Bar, CartesianGrid, ComposedChart, Line, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { CategoryConfig, Demand, StatusConfig } from '../../types';
import { formatCalendarDate, isCalendarDateOverdue } from '../../utils/date';
import { AnimatedNumber } from '../common/AnimatedNumber';
import { MOTION_EASE_OUT } from '../motion/presets';
import { ReportConfiguration } from './reportBuilder';

type Props={id?:string;demands:Demand[];categories:CategoryConfig[];statuses:StatusConfig[];clientFilterText:string;teamFilterText:string;periodText:string;periodStart?:Date|null;configuration:ReportConfiguration;onConfigure?:()=>void};
type Tone='blue'|'slate'|'green'|'amber'|'red'|'rose';
const tones:Record<Tone,{dot:string;icon:string}>={blue:{dot:'bg-blue-500',icon:'bg-blue-50 text-blue-600 dark:bg-blue-500/15 dark:text-blue-300'},slate:{dot:'bg-slate-400',icon:'bg-slate-100 text-slate-600 dark:bg-white/10 dark:text-white'},green:{dot:'bg-emerald-500',icon:'bg-emerald-50 text-emerald-600 dark:bg-emerald-500/15 dark:text-emerald-300'},amber:{dot:'bg-amber-500',icon:'bg-amber-50 text-amber-600 dark:bg-amber-500/15 dark:text-amber-300'},red:{dot:'bg-red-500',icon:'bg-red-50 text-red-600 dark:bg-red-500/15 dark:text-red-300'},rose:{dot:'bg-rose-500',icon:'bg-rose-50 text-rose-600 dark:bg-rose-500/15 dark:text-rose-300'}};
const reveal={initial:{opacity:0,y:16},whileInView:{opacity:1,y:0},viewport:{once:true,margin:'-30px'},transition:{duration:.45,ease:MOTION_EASE_OUT}} as const;
const Heading=({index,title}:{index:string;title:string})=><div className="mb-3 mt-6 flex items-center gap-3"><span className="font-mono text-[10px] font-bold text-slate-300 dark:text-slate-600">{index}</span><span className="h-px w-6 bg-slate-300 dark:bg-slate-700"/><h2 className="text-xs font-black uppercase tracking-[.08em] text-slate-700 dark:text-slate-200">{title}</h2></div>;
const Surface=({children,className=''}:{children:React.ReactNode;className?:string})=><div className={`rounded-2xl border border-slate-200/80 bg-white shadow-sm dark:border-slate-700 dark:bg-slate-900 ${className}`}>{children}</div>;
const initials=(name:string)=>name.split(/\s+/).filter(Boolean).slice(0,2).map(part=>part[0]).join('').toUpperCase();

export const ExecutiveOverviewReport:React.FC<Props>=({id,demands,statuses,clientFilterText,teamFilterText,periodText,periodStart,configuration})=>{
 const reduced=useReducedMotion();const statusMap=useMemo(()=>new Map(statuses.map(item=>[item.id,item])),[statuses]);
 const now=new Date(),reference=periodStart||now,quarter=Math.floor(reference.getMonth()/3)+1,year=reference.getFullYear();
 const completed=demands.filter(item=>statusMap.get(item.statusId)?.category==='completed');const cancelled=demands.filter(item=>statusMap.get(item.statusId)?.category==='cancelled');
 const open=Math.max(0,demands.length-completed.length-cancelled.length);const overdue=demands.filter(item=>statusMap.get(item.statusId)?.category!=='completed'&&isCalendarDateOverdue(item.dueDate));const blocked=demands.filter(item=>item.blocker?.isBlocked);
 const commitment=Math.max(completed.length,demands.filter(item=>{const due=new Date(`${item.dueDate}T12:00:00`);return due.getFullYear()===year&&Math.floor(due.getMonth()/3)+1===quarter;}).length);
 const attainment=commitment?Math.round(completed.length/commitment*100):0;const projected=Math.min(commitment,Math.round(completed.length+open*Math.max(.2,attainment/100)*.45));const projectionRate=commitment?Math.round(projected/commitment*100):0;
 const onTime=completed.length?Math.round(completed.filter(item=>!item.sla?.isBreached).length/completed.length*100):100;const monthlyPace=Math.round(completed.length/3);
 let cumulative=0;const chart=Array.from({length:3},(_,index)=>{const start=new Date(year,(quarter-1)*3+index,1),end=new Date(year,start.getMonth()+1,1);const planned=demands.filter(item=>{const date=new Date(`${item.dueDate}T12:00:00`);return date>=start&&date<end;}).length;const realized=completed.filter(item=>{const date=new Date(item.completedAt||item.dueDate);return date>=start&&date<end;}).length;cumulative+=planned;return{mes:start.toLocaleDateString('pt-BR',{month:'short'}).replace('.',''),planejado:planned,realizado:realized,meta:cumulative};});
 const risks=[...(configuration.riskItems||[])].sort((a,b)=>a.order-b.order).slice(0,5);
 const autoImpacts=[...completed].sort((a,b)=>(b.financials?.benefitValue||0)-(a.financials?.benefitValue||0)).slice(0,4).map(item=>({id:item.id,title:item.title,outcome:item.expectedOutcome||'Entrega concluída com impacto para a operação'}));const impacts=(configuration.impactItems||[]).length?[...configuration.impactItems].sort((a,b)=>a.order-b.order).slice(0,4):autoImpacts;
 const autoMilestones=[...demands].filter(item=>statusMap.get(item.statusId)?.category!=='completed').sort((a,b)=>a.dueDate.localeCompare(b.dueDate)).slice(0,4).map(item=>({id:item.id,title:item.title,dueDate:item.dueDate,progress:item.progressPercent,risk:isCalendarDateOverdue(item.dueDate)?'high' as const:item.blocker?.isBlocked?'medium' as const:'low' as const}));const milestones=(configuration.milestoneItems||[]).length?[...configuration.milestoneItems].sort((a,b)=>a.order-b.order).slice(0,4):autoMilestones;
 const kpis=[{icon:ClipboardList,value:demands.length,label:'Carteira total',tone:'blue' as Tone,featured:true},{icon:Target,value:commitment,label:'Compromisso trimestral',tone:'slate' as Tone},{icon:CheckCircle2,value:completed.length,label:'Entregues no trimestre',tone:'green' as Tone},{icon:TrendingUp,value:attainment,suffix:'%',label:'Atingimento da meta',tone:'amber' as Tone},{icon:AlertTriangle,value:overdue.length,label:'Vencidas',tone:'red' as Tone},{icon:Ban,value:blocked.length,label:'Impedidas',tone:'rose' as Tone}];const animation=reduced?{}:reveal;
 return <div id={id} className="report-executive-theme w-full rounded-2xl bg-slate-50 p-4 text-slate-900 transition-colors dark:bg-slate-950 dark:text-slate-100 sm:p-6 print:bg-white print:p-3">
  <motion.header initial={reduced?false:{opacity:0,y:-16}} animate={{opacity:1,y:0}} transition={{duration:.5,ease:MOTION_EASE_OUT}} className="relative overflow-hidden rounded-2xl bg-slate-900 p-6 text-white shadow-lg sm:p-8"><div className="absolute -right-16 -top-16 h-48 w-48 rounded-full bg-blue-500/20 blur-3xl"/><div className="absolute -bottom-20 left-1/3 h-40 w-40 rounded-full bg-indigo-500/10 blur-3xl"/><div className="relative flex flex-col gap-6 lg:flex-row lg:items-end lg:justify-between"><div><div className="flex items-center gap-2 text-[10px] font-bold uppercase tracking-[.2em] text-blue-300"><span className="h-px w-8 bg-blue-400/60"/>Relatório executivo</div><h1 className="mt-3 text-2xl font-black tracking-tight sm:text-3xl lg:text-4xl">Demandas — {quarter}º Trimestre</h1><div className="mt-4 space-y-1.5 text-xs text-slate-300 sm:text-sm"><p><span className="text-slate-400">Cliente solicitante:</span> <b className="text-white">{clientFilterText}</b></p><p><span className="text-slate-400">Equipe responsável:</span> <b className="text-white">{teamFilterText}</b></p></div></div><div className="shrink-0 rounded-xl border border-white/10 bg-white/5 px-4 py-3 text-sm backdrop-blur"><div className="flex items-center gap-2"><CalendarClock className="h-4 w-4 text-blue-300"/><b>{periodText.replace(' a ',' → ')}</b></div><div className="mt-2 flex items-center gap-2 text-xs text-slate-400"><RefreshCw className="h-3.5 w-3.5"/>Atualizado em {now.toLocaleDateString('pt-BR')}</div></div></div></motion.header>
  <Heading index="01" title="Indicadores"/><div className="grid grid-cols-2 gap-3 md:grid-cols-3 xl:grid-cols-6">{kpis.map((item,index)=>{const Icon=item.icon;return <motion.div key={item.label} initial={reduced?false:{opacity:0,y:16}} animate={{opacity:1,y:0}} transition={{delay:.05*index,duration:.45,ease:MOTION_EASE_OUT}} whileHover={reduced?undefined:{y:-3}} className={`rounded-2xl p-4 shadow-sm hover:shadow-md ${item.featured?'bg-slate-900 text-white':'border border-slate-200/80 bg-white dark:border-slate-700 dark:bg-slate-900'}`}><div className="flex items-center justify-between"><span className={`grid h-9 w-9 place-items-center rounded-lg ${item.featured?'bg-white/10 text-white':tones[item.tone].icon}`}><Icon className="h-5 w-5"/></span><span className={`h-2 w-2 rounded-full ${tones[item.tone].dot}`}/></div><AnimatedNumber value={item.value} suffix={item.suffix} delay={index*50} className={`mt-4 block text-3xl font-black tracking-tight sm:text-4xl ${item.featured?'text-white':'text-slate-900 dark:text-white'}`}/><span className={`mt-1 block text-[11px] font-medium ${item.featured?'text-slate-300':'text-slate-500 dark:text-slate-400'}`}>{item.label}</span></motion.div>})}</div>
  <Heading index="02" title="Síntese & projeção"/><div className="grid gap-4 lg:grid-cols-5"><motion.div {...animation} className="lg:col-span-3"><Surface className="h-full p-6"><Label>Síntese</Label><p className="mt-4 text-sm leading-7 text-slate-600 dark:text-slate-300">A carteira mantém <strong className="text-slate-900 dark:text-white">{commitment} demandas comprometidas</strong>, com <strong className="text-emerald-600">{completed.length} entregas concluídas</strong>. O ritmo projeta <strong className="text-blue-600 dark:text-blue-400">{projected} entregas</strong>, ou <strong className="text-blue-600 dark:text-blue-400">{projectionRate}%</strong> da meta. Há <strong className="text-red-600">{overdue.length} vencidas</strong> e <strong className="text-rose-600">{blocked.length} impedidas</strong> que demandam acompanhamento.</p></Surface></motion.div><motion.div {...animation} className="relative overflow-hidden rounded-2xl bg-gradient-to-br from-blue-600 to-indigo-700 p-6 text-white shadow-lg lg:col-span-2"><div className="absolute -right-10 -top-10 h-32 w-32 rounded-full bg-white/10 blur-2xl"/><div className="relative"><div className="flex justify-between text-[10px] font-bold uppercase tracking-[.15em] text-blue-100"><span className="flex gap-2"><TrendingUp className="h-4 w-4"/>Projeção</span><ArrowUpRight className="h-5 w-5"/></div><AnimatedNumber value={projectionRate} suffix="%" className="mt-5 block text-6xl font-black"/><p className="mt-2 text-sm text-blue-100"><b className="text-white">{projected}</b> de <b className="text-white">{commitment}</b> entregas projetadas</p><div className="mt-4 h-2 overflow-hidden rounded-full bg-white/20"><motion.div initial={{width:0}} whileInView={{width:`${Math.min(100,projectionRate)}%`}} viewport={{once:true}} transition={{duration:1,ease:MOTION_EASE_OUT}} className="h-full rounded-full bg-white"/></div></div></motion.div></div>
  <Heading index="03" title="Evolução & saúde"/><div className="grid gap-4 xl:grid-cols-[1.65fr_.75fr]"><motion.div {...animation}><Surface className="h-full p-6"><div className="flex flex-wrap justify-between gap-2"><Label>Evolução do trimestre</Label><div className="flex gap-3 text-[10px] text-slate-500"><span>● Planejado</span><span className="text-teal-500">● Realizado</span><span className="text-emerald-500">● Meta</span></div></div><div className="mt-4 h-64"><ResponsiveContainer><ComposedChart data={chart} barGap={6}><CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#dbe3ee"/><XAxis dataKey="mes" tick={{fontSize:11,fill:'#94a3b8'}} axisLine={false} tickLine={false}/><YAxis tick={{fontSize:11,fill:'#94a3b8'}} axisLine={false} tickLine={false} width={28}/><Tooltip contentStyle={{borderRadius:12,border:'1px solid #cbd5e1',fontSize:12,color:'#0f172a'}}/><Bar dataKey="planejado" name="Planejado" fill="#1e3a8a" radius={[6,6,0,0]}/><Bar dataKey="realizado" name="Realizado" fill="#14b8a6" radius={[6,6,0,0]}/><Line dataKey="meta" name="Meta acumulada" stroke="#10b981" strokeWidth={2.5} dot={{r:4,fill:'#10b981'}}/></ComposedChart></ResponsiveContainer></div></Surface></motion.div><motion.div {...animation}><Surface className="h-full p-6"><div className="flex items-center justify-between"><Label>Saúde do portfólio</Label><span className={`rounded-full px-3 py-1 text-[10px] font-bold ring-1 ${overdue.length||blocked.length?'bg-amber-50 text-amber-700 ring-amber-200 dark:bg-amber-500/10 dark:text-amber-300':'bg-emerald-50 text-emerald-700 ring-emerald-200'}`}><i className="mr-1 inline-block h-1.5 w-1.5 animate-pulse rounded-full bg-current"/>{overdue.length||blocked.length?'EM ATENÇÃO':'SAUDÁVEL'}</span></div><div className="mt-5 grid grid-cols-2 gap-3"><Health icon={ShieldCheck} value={onTime} suffix="%" label="dentro do prazo" tone="green"/><Health icon={Clock3} value={overdue.length} label="vencidas" tone="red"/><Health icon={Ban} value={blocked.length} label="impedidas" tone="rose"/><Health icon={TrendingUp} value={monthlyPace} label="entregas/mês" tone="blue"/></div></Surface></motion.div></div>
  {configuration.showRisksAndDecisions&&<><Heading index="04" title="Riscos & decisões"/><motion.div {...animation}><Surface className="overflow-hidden p-5"><div className="overflow-x-auto rounded-xl border border-slate-100 dark:border-slate-700"><table className="w-full min-w-[760px] text-left text-xs"><thead><tr className="bg-slate-50 uppercase tracking-wide text-slate-500 dark:bg-slate-800">{['Demanda','Impacto','Responsável','Prazo','Decisão necessária'].map(label=><th key={label} className="px-4 py-3 font-bold">{label}</th>)}</tr></thead><tbody className="divide-y divide-slate-100 dark:divide-slate-700">{risks.length?risks.map(item=><tr key={item.id} className="hover:bg-slate-50/80 dark:hover:bg-slate-800/60"><td className="px-4 py-3.5"><div className="font-mono text-[10px] font-bold text-blue-600">{item.demandName.split(' — ')[0]}</div><div className="mt-0.5 font-semibold">{item.demandName.split(' — ').slice(1).join(' — ')||item.demandName}</div></td><td className="px-4 py-3.5 text-slate-600 dark:text-slate-300">{item.impact}</td><td className="px-4 py-3.5"><span className="inline-flex items-center gap-2"><i className="grid h-7 w-7 place-items-center rounded-full bg-slate-200 text-[10px] font-bold text-slate-600 dark:bg-slate-700 dark:text-slate-200">{initials(item.responsible)}</i>{item.responsible}</span></td><td className="px-4 py-3.5 font-semibold">{item.resolutionDueDate?formatCalendarDate(item.resolutionDueDate):'A definir'}</td><td className="px-4 py-3.5"><span className="inline-flex max-w-56 items-center gap-1 rounded-full bg-amber-50 px-3 py-1.5 text-[10px] font-semibold text-amber-700 ring-1 ring-amber-200 dark:bg-amber-500/10 dark:text-amber-300">{item.decision}<ChevronRight className="h-3.5 w-3.5 shrink-0"/></span></td></tr>):<tr><td colSpan={5} className="p-8 text-center text-slate-400">Nenhum risco selecionado.</td></tr>}</tbody></table></div></Surface></motion.div></>}
  {(configuration.showImpactDeliveries!==false||configuration.showMilestones!==false)&&<><Heading index={configuration.showRisksAndDecisions?'05':'04'} title="Entregas & marcos"/><div className="grid gap-4 lg:grid-cols-2">{configuration.showImpactDeliveries!==false&&<motion.div {...animation}><Surface className="h-full p-5"><div className="space-y-3">{impacts.map(item=><div key={item.id} className="flex items-start gap-3 rounded-xl border border-slate-100 bg-slate-50/50 p-3 dark:border-slate-700 dark:bg-slate-800/50"><CheckCircle2 className="mt-0.5 h-5 w-5 shrink-0 text-emerald-500"/><div><div className="text-sm font-semibold">{item.title}</div><div className="text-xs text-slate-500">— {item.outcome}</div></div></div>)}</div></Surface></motion.div>}{configuration.showMilestones!==false&&<motion.div {...animation}><Surface className="h-full p-5"><div className="space-y-3">{milestones.map(item=><Milestone key={item.id} item={item}/>)}</div></Surface></motion.div>}</div></>}
  <footer className="mt-6 border-t border-slate-200 px-2 py-3 text-[10px] text-slate-400 dark:border-slate-700">Fonte: Sistema de Gestão de Demandas &nbsp;|&nbsp; Dados consolidados no momento da emissão</footer>
 </div>;
};
const Label=({children}:{children:React.ReactNode})=><h3 className="text-[10px] font-bold uppercase tracking-[.15em] text-slate-400">{children}</h3>;
const Health=({icon:Icon,value,suffix='',label,tone}:{icon:React.ElementType;value:number;suffix?:string;label:string;tone:Tone})=><div className="flex items-center gap-3 rounded-xl border border-slate-100 bg-slate-50/40 p-3 dark:border-slate-700 dark:bg-slate-800/50"><span className={`grid h-10 w-10 shrink-0 place-items-center rounded-xl ${tones[tone].icon}`}><Icon className="h-5 w-5"/></span><div><AnimatedNumber value={value} suffix={suffix} className="text-2xl font-black"/><div className="text-[10px] text-slate-500">{label}</div></div></div>;
const Milestone:React.FC<{item:{id:string;title:string;dueDate:string;progress:number;risk:'low'|'medium'|'high'}}> = ({item})=>{const risk=item.risk==='high'?'Alto':item.risk==='medium'?'Médio':'Baixo';return <div className="rounded-xl border border-slate-100 p-3 dark:border-slate-700"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><div className="truncate text-sm font-semibold">{item.title}</div><div className="text-xs text-slate-500">{formatCalendarDate(item.dueDate)}</div></div><span className={`rounded-full px-2.5 py-0.5 text-[10px] font-bold ring-1 ${risk==='Alto'?'bg-red-50 text-red-600 ring-red-200 dark:bg-red-500/10':risk==='Médio'?'bg-amber-50 text-amber-600 ring-amber-200':'bg-emerald-50 text-emerald-600 ring-emerald-200'}`}>{risk}</span></div><div className="mt-2.5 flex items-center gap-2"><div className="h-1.5 flex-1 overflow-hidden rounded-full bg-slate-100 dark:bg-slate-700"><motion.div initial={{width:0}} whileInView={{width:`${item.progress}%`}} viewport={{once:true}} transition={{duration:1,ease:MOTION_EASE_OUT}} className="h-full rounded-full bg-gradient-to-r from-amber-400 to-amber-500"/></div><span className="w-9 text-right text-xs font-bold">{item.progress}%</span></div></div>};
