import React, { useState } from 'react';
import { ChevronDown, FileBarChart, RotateCcw, Save, X } from 'lucide-react';
import { CategoryConfig, Demand, PriorityConfig, StatusConfig, Team, User } from '../../types';
import { AppSelect } from '../common/AppSelect';
import { EVOLUTION_SERIES, isReportImpactValid, isReportMilestoneValid, isReportRiskValid, REPORT_BLOCKS, REPORT_KPIS, ReportConfiguration, ReportPreset } from './reportBuilder';
import { RisksDecisionsConfigurator } from './RisksDecisionsConfigurator';
import { ExecutiveItemsConfigurator } from './ExecutiveItemsConfigurator';

type Client={id:string;name:string;company:string;active:boolean};
type Props={open:boolean;config:ReportConfiguration;demands:Demand[];statuses:StatusConfig[];categories:CategoryConfig[];priorities:PriorityConfig[];users:User[];teams:Team[];clients:Client[];presets:ReportPreset[];onChange:(config:ReportConfiguration)=>void;onCancel:()=>void;onClose:()=>void;onRestore:()=>void;onSave:(name:string)=>Promise<void>;onLoad:(preset:ReportPreset)=>void;onNativePreset:(name:'Executivo'|'Gerencial'|'Completo')=>void};
const ToggleList=<T extends string>({items,selected,onChange}:{items:Array<{id:T;label:string}>;selected:T[];onChange:(value:T[])=>void})=>{const toggle=(id:T)=>onChange(selected.includes(id)?selected.filter(item=>item!==id):[...selected,id]);return <div className="grid grid-cols-1 gap-2 sm:grid-cols-2">{items.map(item=><label key={item.id} className="flex cursor-pointer items-start gap-2 rounded-lg border border-slate-200 bg-slate-50 p-2 text-xs dark:border-slate-700 dark:bg-slate-800"><input type="checkbox" checked={selected.includes(item.id)} onChange={()=>toggle(item.id)} className="mt-0.5 accent-blue-600"/><strong>{item.label}</strong></label>)}</div>};
const Section=({title,children,open=true}:{title:string;children:React.ReactNode;open?:boolean})=><details open={open} className="rounded-xl border border-slate-200 bg-white dark:border-slate-800 dark:bg-slate-900"><summary className="flex cursor-pointer list-none items-center justify-between p-3 text-sm font-bold">{title}<ChevronDown className="h-4 w-4"/></summary><div className="border-t border-slate-100 p-3 dark:border-slate-800">{children}</div></details>;

export const ReportBuilderDrawer:React.FC<Props>=({open,config,demands,statuses,categories,priorities,users,teams,clients,presets,onChange,onCancel,onClose,onRestore,onSave,onLoad,onNativePreset})=>{
 const [name,setName]=useState('');const [saving,setSaving]=useState(false);if(!open)return null;
 const set=<K extends keyof ReportConfiguration>(key:K,value:ReportConfiguration[K])=>onChange({...config,[key]:value});const riskItems=config.riskItems||[];const impactItems=config.impactItems||[];const milestoneItems=config.milestoneItems||[];const reportValid=(!config.showRisksAndDecisions||(riskItems.length>0&&riskItems.every(isReportRiskValid)))&&(!config.showImpactDeliveries||!impactItems.length||impactItems.every(isReportImpactValid))&&(!config.showMilestones||!milestoneItems.length||milestoneItems.every(isReportMilestoneValid));
 const save=async()=>{if(!name.trim())return;setSaving(true);try{await onSave(name.trim());setName('');}finally{setSaving(false);}};
 return <div className="fixed inset-0 z-[90] bg-slate-950/35" onMouseDown={event=>{if(event.target===event.currentTarget)onCancel();}}><aside className="ml-auto flex h-full w-full max-w-3xl flex-col border-l border-slate-200 bg-slate-50 shadow-2xl dark:border-slate-800 dark:bg-slate-950" onMouseDown={event=>event.stopPropagation()}>
  <header className="flex items-start justify-between border-b border-slate-200 bg-white p-5 dark:border-slate-800 dark:bg-slate-900"><div><h2 className="text-lg font-black">Configuração do Relatório</h2><p className="mt-1 text-xs text-slate-500">Configure, revise e emita a fotografia executiva do período.</p></div><button onClick={onCancel}><X className="h-5 w-5"/></button></header>
  <div className="border-b border-slate-200 bg-white px-4 py-3 dark:border-slate-800 dark:bg-slate-900"><ol className="grid grid-cols-3 gap-2 text-[10px] font-bold text-slate-500 lg:grid-cols-6">{['Período e equipe','Indicadores','Riscos e decisões','Entregas de impacto','Próximos marcos','Revisão e emissão'].map((step,index)=><li key={step} className={`rounded-lg border p-2 ${index===2?'border-blue-500 bg-blue-50 text-blue-700 dark:bg-blue-950':''}`}>{index+1}. {step}</li>)}</ol></div>
  <div className="flex-1 space-y-3 overflow-y-auto p-4">
   <Section title="Configurações rápidas"><div className="grid grid-cols-3 gap-2">{(['Executivo','Gerencial','Completo'] as const).map(item=><button key={item} onClick={()=>onNativePreset(item)} className="rounded-lg bg-blue-50 px-3 py-2 text-xs font-bold text-blue-700 dark:bg-blue-950">{item}</button>)}</div>{presets.length>0&&<AppSelect className="mt-3 w-full" defaultValue="" onChange={event=>{const preset=presets.find(item=>item.id===event.target.value);if(preset)onLoad(preset);}}><option value="">Carregar configuração salva...</option>{presets.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</AppSelect>}</Section>
   <Section title="Indicadores e conteúdo"><p className="mb-2 text-xs font-bold">Indicadores principais</p><ToggleList items={REPORT_KPIS.map(item=>({id:item.key,label:item.label}))} selected={config.kpis} onChange={value=>set('kpis',value)}/><p className="mb-2 mt-4 text-xs font-bold">Seções</p><ToggleList items={REPORT_BLOCKS.map(item=>({id:item.key,label:item.label}))} selected={config.blocks} onChange={value=>set('blocks',value)}/></Section>
   <Section title="3. Riscos e decisões necessárias"><RisksDecisionsConfigurator enabled={Boolean(config.showRisksAndDecisions)} items={riskItems} demands={demands} users={users} teams={teams} statuses={statuses} onEnabledChange={value=>set('showRisksAndDecisions',value)} onChange={value=>set('riskItems',value)}/></Section>
   <Section title="4. Entregas de maior impacto"><ExecutiveItemsConfigurator mode="impact" enabled={config.showImpactDeliveries!==false} items={impactItems} demands={demands} statuses={statuses} onEnabledChange={value=>set('showImpactDeliveries',value)} onChange={value=>set('impactItems',value)}/></Section>
   <Section title="5. Próximos marcos"><ExecutiveItemsConfigurator mode="milestone" enabled={config.showMilestones!==false} items={milestoneItems} demands={demands} statuses={statuses} onEnabledChange={value=>set('showMilestones',value)} onChange={value=>set('milestoneItems',value)}/></Section>
   <Section title="Status e tipos de demanda" open={false}><ToggleList items={statuses.map(item=>({id:item.id,label:item.name}))} selected={config.statusIds} onChange={value=>set('statusIds',value)}/><div className="mt-3"><ToggleList items={categories.map(item=>({id:item.id,label:item.name}))} selected={config.categoryIds} onChange={value=>set('categoryIds',value)}/></div></Section>
   <Section title="Filtros complementares" open={false}><p className="mb-3 text-xs text-slate-500">Usuários, equipes, clientes e período são definidos na barra principal para evitar filtros conflitantes. Aqui você pode restringir as prioridades.</p><ToggleList items={priorities.map(item=>({id:item.id,label:item.name}))} selected={config.priorityIds} onChange={value=>set('priorityIds',value)}/></Section>
   <Section title="Evolução e resumo" open={false}><ToggleList items={EVOLUTION_SERIES.map(item=>({id:item.key,label:item.label}))} selected={config.evolutionSeries} onChange={value=>set('evolutionSeries',value)}/><AppSelect value={config.evolutionMonths} onChange={event=>set('evolutionMonths',Number(event.target.value) as 3|6|12)} className="mt-3"><option value={3}>3 meses</option><option value={6}>6 meses</option><option value={12}>12 meses</option></AppSelect><label className="mt-3 flex gap-2 text-xs"><input type="checkbox" checked={config.autoSummary} onChange={event=>set('autoSummary',event.target.checked)}/>Gerar resumo executivo</label><label className="mt-2 flex gap-2 text-xs"><input type="checkbox" checked={config.includeRecommendation} onChange={event=>set('includeRecommendation',event.target.checked)}/>Incluir recomendação gerencial</label></Section>
   <Section title="Salvar rascunho"><div className="flex gap-2"><input value={name} onChange={event=>setName(event.target.value)} placeholder="Nome do modelo" className="min-w-0 flex-1 rounded-lg border p-2 text-xs dark:bg-slate-800"/><button disabled={!name.trim()||saving||!reportValid} onClick={save} className="rounded-lg bg-emerald-600 px-3 text-xs font-bold text-white disabled:opacity-50"><Save className="mr-1 inline h-3.5 w-3.5"/>{saving?'Salvando...':'Salvar rascunho'}</button></div></Section>
  </div>
  <footer className="flex flex-wrap justify-end gap-2 border-t border-slate-200 bg-white p-4 dark:border-slate-800 dark:bg-slate-900"><button onClick={onCancel} className="rounded-lg px-3 py-2 text-xs font-bold">Voltar</button><button onClick={onRestore} className="rounded-lg border px-3 py-2 text-xs font-bold"><RotateCcw className="mr-1 inline h-3.5 w-3.5"/>Restaurar padrão</button><button disabled={!reportValid} onClick={onClose} className="rounded-lg bg-blue-600 px-4 py-2 text-xs font-bold text-white disabled:opacity-50"><FileBarChart className="mr-1 inline h-4 w-4"/>Visualizar relatório</button></footer>
 </aside></div>;
};
