import React, { useState } from 'react';
import { Building2, X } from 'lucide-react';
import { apiClient } from '../../services/apiClient';

export type ClientRecord = { id: string; name: string; company: string; email: string; phone: string; active: boolean; createdAt: string };

export const ClientModal: React.FC<{ isOpen: boolean; onClose: () => void; onCreated: (client: ClientRecord) => void }> = ({ isOpen, onClose, onCreated }) => {
  const [name, setName] = useState(''); const [company, setCompany] = useState(''); const [email, setEmail] = useState(''); const [phone, setPhone] = useState('');
  if (!isOpen) return null;
  const submit = async (event: React.FormEvent) => { event.preventDefault(); const client = await apiClient.createClient({ name: name.trim(), company: company.trim(), email: email.trim().toLowerCase(), phone: phone.trim(), active: true }) as ClientRecord; window.dispatchEvent(new CustomEvent('prolog:clients-updated')); onCreated(client); setName(''); setCompany(''); setEmail(''); setPhone(''); onClose(); };
  const field = 'mt-1.5 w-full h-11 px-3 rounded-xl border border-slate-300 dark:border-slate-700 bg-slate-50 dark:bg-slate-800';
  return <div className="fixed inset-0 z-50 grid place-items-center p-4 bg-slate-950/60 backdrop-blur-sm"><div className="w-full max-w-lg rounded-3xl bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 shadow-2xl overflow-hidden"><header className="p-5 border-b border-slate-200 dark:border-slate-800 flex items-center justify-between"><div className="flex items-center gap-3"><span className="w-10 h-10 rounded-xl bg-emerald-50 dark:bg-emerald-950 text-emerald-600 grid place-items-center"><Building2 className="w-5 h-5" /></span><div><h2 className="font-black text-slate-900 dark:text-white">Novo Cliente</h2><p className="text-xs text-slate-500">Cadastre o solicitante externo das demandas</p></div></div><button type="button" onClick={onClose} aria-label="Fechar" className="p-2 text-slate-400"><X className="w-5 h-5" /></button></header><form onSubmit={submit} className="p-6 space-y-4"><div className="grid sm:grid-cols-2 gap-3"><label className="text-xs font-bold">Nome do contato *<input required value={name} onChange={e => setName(e.target.value)} className={field} /></label><label className="text-xs font-bold">Empresa / Cliente *<input required value={company} onChange={e => setCompany(e.target.value)} className={field} /></label><label className="text-xs font-bold">E-mail *<input required type="email" value={email} onChange={e => setEmail(e.target.value)} className={field} /></label><label className="text-xs font-bold">Telefone / WhatsApp<input value={phone} onChange={e => setPhone(e.target.value)} className={field} /></label></div><div className="flex justify-end gap-2 pt-2"><button type="button" onClick={onClose} className="px-4 py-2.5 text-xs font-bold text-slate-500">Cancelar</button><button className="px-4 py-2.5 rounded-xl bg-emerald-600 text-white text-xs font-bold">Cadastrar Cliente</button></div></form></div></div>;
};
