import React from 'react';
import { AlertCircle, ArrowRight, Boxes, Briefcase, Code2, FolderKanban, LogOut, RefreshCw, Scale, Truck, Users, Warehouse, Workflow } from 'lucide-react';
import type { AuthorizedModuleDto } from '../../contracts';

const icons={Briefcase,Code2,Workflow,FolderKanban,Warehouse,Truck,Scale,Users,Boxes};
export const ModuleSelector:React.FC<{modules:AuthorizedModuleDto[];error:string;onSelect:(module:AuthorizedModuleDto)=>void;onRetry:()=>Promise<void>}>=({modules,error,onSelect,onRetry})=><main className="min-h-dvh bg-slate-50 px-5 py-10 sm:p-10">
  <div className="mx-auto max-w-5xl">
    <header className="flex items-center justify-between gap-4"><div className="flex items-center gap-3"><div className="grid h-11 w-11 place-items-center rounded-2xl bg-blue-600 text-xl font-black text-white">P</div><div><p className="text-lg font-black text-slate-950">PROLOG</p><p className="text-xs text-slate-500">Selecione sua área de trabalho</p></div></div><button onClick={()=>window.dispatchEvent(new CustomEvent('prolog:logout'))} className="inline-flex items-center gap-2 rounded-xl border border-slate-300 bg-white px-3 py-2 text-xs font-bold text-slate-700 hover:bg-slate-100 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-blue-600"><LogOut className="h-4 w-4"/>Sair</button></header>
    <section className="mt-12" aria-labelledby="module-selector-title"><p className="text-xs font-extrabold uppercase tracking-[0.18em] text-blue-600">Áreas autorizadas</p><h1 id="module-selector-title" className="mt-2 text-3xl font-black tracking-tight text-slate-950">Em qual módulo você vai trabalhar?</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-slate-600">Cada módulo mantém demandas, quadros e configurações da área separados. Você poderá trocar depois pelo cabeçalho.</p>
      {error&&<div role="alert" className="mt-6 flex items-start gap-3 rounded-2xl border border-red-200 bg-red-50 p-4 text-sm text-red-900"><AlertCircle className="mt-0.5 h-5 w-5 shrink-0"/><div className="flex-1"><p className="font-bold">Não foi possível carregar seus módulos</p><p className="mt-1">{error}</p></div><button onClick={()=>void onRetry()} className="rounded-lg p-2 hover:bg-red-100" aria-label="Tentar novamente"><RefreshCw className="h-4 w-4"/></button></div>}
      {!error&&modules.length===0&&<div className="mt-8 rounded-2xl border border-slate-200 bg-white p-8 text-center"><FolderKanban className="mx-auto h-10 w-10 text-slate-400"/><h2 className="mt-4 font-black text-slate-900">Nenhum módulo disponível</h2><p className="mt-2 text-sm text-slate-600">Seu acesso está ativo, mas ainda não há vínculo com uma área operacional. Solicite a inclusão a um administrador.</p></div>}
      <div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{modules.map(module=>{const Icon=icons[module.icon];return <button key={module.id} onClick={()=>onSelect(module)} className="group flex min-h-48 flex-col rounded-2xl border border-slate-200 bg-white p-5 text-left shadow-sm transition hover:-translate-y-0.5 hover:border-blue-300 hover:shadow-lg focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-blue-600"><div className="flex items-start justify-between"><span className="grid h-11 w-11 place-items-center rounded-xl text-white" style={{backgroundColor:module.color}}><Icon className="h-5 w-5"/></span><ArrowRight className="h-5 w-5 text-slate-300 transition group-hover:translate-x-1 group-hover:text-blue-600"/></div><h2 className="mt-5 text-lg font-black text-slate-950">{module.name}</h2><p className="mt-2 line-clamp-2 text-sm leading-5 text-slate-600">{module.description||'Área operacional do PROLOG.'}</p><span className="mt-auto pt-4 text-xs font-bold uppercase tracking-wide text-blue-700">{module.role.replace('_',' ')}</span></button>})}</div>
    </section>
  </div>
</main>;
