import React, { useCallback, useEffect, useMemo, useState } from 'react';
import { AlertCircle, Archive, Boxes, Plus, RefreshCw, Save, UserPlus } from 'lucide-react';
import type { ModuleDto, ModuleRole } from '../../contracts';
import { useApp } from '../../context/AppContext';
import { apiClient } from '../../services/apiClient';

const roles:Array<{value:ModuleRole;label:string}>=[{value:'module_admin',label:'Administrador do módulo'},{value:'manager',label:'Gestor'},{value:'member',label:'Membro'},{value:'viewer',label:'Somente leitura'}];
export const ModulesManagement:React.FC=()=>{
  const {currentUser,users}=useApp();
  const [modules,setModules]=useState<ModuleDto[]>([]);const [selected,setSelected]=useState<ModuleDto|null>(null);const [members,setMembers]=useState<Awaited<ReturnType<typeof apiClient.moduleMembers>>>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState('');
  const [form,setForm]=useState({name:'',slug:'',description:'',icon:'FolderKanban' as const,color:'#2563eb'});const [memberUserId,setMemberUserId]=useState('');const [memberRole,setMemberRole]=useState<ModuleRole>('member');
  const load=useCallback(async()=>{setLoading(true);setError('');try{const result=await apiClient.modules({page:1,pageSize:100});setModules(result.items);setSelected(previous=>result.items.find(item=>item.id===previous?.id)??result.items[0]??null);}catch(cause){setError(cause instanceof Error?cause.message:'Falha ao carregar módulos.');}finally{setLoading(false);}},[]);
  useEffect(()=>{void load();},[load]);useEffect(()=>{if(!selected){setMembers([]);return;}apiClient.moduleMembers(selected.id).then(setMembers).catch(cause=>setError(cause instanceof Error?cause.message:'Falha ao carregar membros.'));},[selected]);
  const availableUsers=useMemo(()=>users.filter(user=>user.active&&!members.some(member=>member.userId===user.id&&member.active)),[users,members]);
  if(currentUser.role!=='admin')return <div role="alert" className="rounded-2xl border border-red-200 bg-red-50 p-6 text-sm text-red-900">A administração global de módulos é restrita ao perfil ADMIN.</div>;
  const create=async(event:React.FormEvent)=>{event.preventDefault();setError('');try{const created=await apiClient.createModule(form);setForm({name:'',slug:'',description:'',icon:'FolderKanban',color:'#2563eb'});await load();setSelected(created);}catch(cause){setError(cause instanceof Error?cause.message:'Não foi possível criar o módulo.');}};
  const toggleActive=async()=>{if(!selected)return;try{const updated=await apiClient.updateModule(selected.id,{active:!selected.active,version:selected.version});await load();setSelected(updated);}catch(cause){setError(cause instanceof Error?cause.message:'Não foi possível alterar o módulo.');}};
  const archive=async()=>{if(!selected||!window.confirm(`Arquivar “${selected.name}”? O histórico será preservado e novas operações serão bloqueadas.`))return;try{await apiClient.deleteModule(selected.id,selected.version);setSelected(null);await load();}catch(cause){setError(cause instanceof Error?cause.message:'Não foi possível arquivar o módulo.');}};
  const addMember=async(event:React.FormEvent)=>{event.preventDefault();if(!selected||!memberUserId)return;try{await apiClient.addModuleMember(selected.id,{userId:memberUserId,role:memberRole});setMemberUserId('');setMembers(await apiClient.moduleMembers(selected.id));}catch(cause){setError(cause instanceof Error?cause.message:'Não foi possível vincular o usuário.');}};
  return <div className="mx-auto max-w-7xl space-y-6"><header className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs font-extrabold uppercase tracking-widest text-blue-600">Administração global</p><h1 className="mt-1 text-2xl font-black text-slate-950 dark:text-white">Módulos operacionais</h1><p className="mt-1 text-sm text-slate-600 dark:text-slate-400">Crie áreas independentes e controle quem participa de cada operação.</p></div><button onClick={()=>void load()} className="rounded-xl border border-slate-300 bg-white p-2.5 text-slate-600 hover:bg-slate-50" aria-label="Atualizar módulos"><RefreshCw className="h-4 w-4"/></button></header>
    {error&&<div role="alert" className="flex gap-2 rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-900"><AlertCircle className="h-5 w-5 shrink-0"/>{error}</div>}
    <div className="grid gap-6 xl:grid-cols-[minmax(300px,0.8fr)_minmax(0,1.6fr)]"><section className="space-y-4"><form onSubmit={create} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900"><h2 className="font-black">Novo módulo</h2><div className="mt-4 space-y-3"><label className="block text-xs font-bold">Nome<input required minLength={2} value={form.name} onChange={event=>setForm(value=>({...value,name:event.target.value,slug:value.slug||event.target.value.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')}))} className="mt-1 w-full rounded-xl border border-slate-300 px-3 py-2.5 text-sm"/></label><label className="block text-xs font-bold">Slug<input required value={form.slug} onChange={event=>setForm(value=>({...value,slug:event.target.value}))} className="mt-1 w-full rounded-xl border border-slate-300 px-3 py-2.5 text-sm"/></label><label className="block text-xs font-bold">Descrição<textarea value={form.description} onChange={event=>setForm(value=>({...value,description:event.target.value}))} className="mt-1 min-h-20 w-full rounded-xl border border-slate-300 px-3 py-2.5 text-sm"/></label><label className="block text-xs font-bold">Cor<input type="color" value={form.color} onChange={event=>setForm(value=>({...value,color:event.target.value}))} className="mt-1 h-10 w-full rounded-xl border border-slate-300 p-1"/></label></div><button className="mt-4 inline-flex w-full items-center justify-center gap-2 rounded-xl bg-blue-600 px-4 py-2.5 text-sm font-bold text-white hover:bg-blue-700"><Plus className="h-4 w-4"/>Criar módulo</button></form>
      <div className="rounded-2xl border border-slate-200 bg-white p-3 dark:border-slate-800 dark:bg-slate-900" aria-busy={loading}>{modules.map(module=><button key={module.id} onClick={()=>setSelected(module)} className={`mb-1 flex w-full items-center justify-between rounded-xl p-3 text-left ${selected?.id===module.id?'bg-blue-50 text-blue-800 dark:bg-blue-950':'hover:bg-slate-50 dark:hover:bg-slate-800'}`}><span><strong className="block text-sm">{module.name}</strong><span className="text-xs opacity-70">/{module.slug}</span></span><span className={`h-2.5 w-2.5 rounded-full ${module.active?'bg-emerald-500':'bg-slate-400'}`}/></button>)}</div></section>
      <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900">{selected?<><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex items-center gap-2"><span className="h-4 w-4 rounded" style={{backgroundColor:selected.color}}/><h2 className="text-xl font-black">{selected.name}</h2></div><p className="mt-2 text-sm text-slate-600 dark:text-slate-400">{selected.description||'Sem descrição.'}</p><p className="mt-2 text-xs text-slate-500">Versão {selected.version} · {selected.counts.users} usuários · {selected.counts.teams} equipes · {selected.counts.demands} demandas</p></div><div className="flex gap-2"><button onClick={()=>void toggleActive()} className="inline-flex items-center gap-2 rounded-xl border border-slate-300 px-3 py-2 text-xs font-bold"><Save className="h-4 w-4"/>{selected.active?'Desativar':'Reativar'}</button><button onClick={()=>void archive()} className="inline-flex items-center gap-2 rounded-xl border border-red-200 px-3 py-2 text-xs font-bold text-red-700"><Archive className="h-4 w-4"/>Arquivar</button></div></div>
        <div className="mt-7 border-t border-slate-200 pt-5"><h3 className="font-black">Pessoas com acesso</h3><form onSubmit={addMember} className="mt-3 grid gap-2 sm:grid-cols-[1fr_220px_auto]"><select required value={memberUserId} onChange={event=>setMemberUserId(event.target.value)} className="rounded-xl border border-slate-300 px-3 py-2.5 text-sm"><option value="">Selecione um usuário</option>{availableUsers.map(user=><option key={user.id} value={user.id}>{user.name}</option>)}</select><select value={memberRole} onChange={event=>setMemberRole(event.target.value as ModuleRole)} className="rounded-xl border border-slate-300 px-3 py-2.5 text-sm">{roles.map(role=><option key={role.value} value={role.value}>{role.label}</option>)}</select><button className="inline-flex items-center justify-center gap-2 rounded-xl bg-slate-900 px-4 py-2 text-sm font-bold text-white"><UserPlus className="h-4 w-4"/>Vincular</button></form><div className="mt-4 divide-y divide-slate-100">{members.map(member=><div key={member.userId} className="flex flex-wrap items-center justify-between gap-3 py-3"><div><p className="text-sm font-bold">{member.userName}</p><p className="text-xs text-slate-500">{member.userEmail}</p></div><select aria-label={`Papel de ${member.userName}`} value={member.role} disabled={!member.active} onChange={async event=>{try{const updated=await apiClient.updateModuleMember(selected.id,member.userId,{role:event.target.value as ModuleRole});setMembers(items=>items.map(item=>item.userId===updated.userId?updated:item));}catch(cause){setError(cause instanceof Error?cause.message:'Falha ao alterar papel.');}}} className="rounded-lg border border-slate-300 px-2 py-1.5 text-xs">{roles.map(role=><option key={role.value} value={role.value}>{role.label}</option>)}</select></div>)}</div></div></>:<div className="grid min-h-80 place-items-center text-center text-slate-500"><div><Boxes className="mx-auto h-10 w-10"/><p className="mt-3 text-sm">Crie ou selecione um módulo.</p></div></div>}</section></div>
  </div>;
};
