import { z } from 'zod'; import { identifierSchema } from './common';
export const categoryConfigDtoSchema=z.object({id:identifierSchema,code:z.string(),name:z.string(),description:z.string(),iconName:z.enum(['Crown','BookOpen','Cog','Sparkles','Layers','Briefcase']),color:z.string(),bgColor:z.string(),textColor:z.string(),borderColor:z.string(),isSystem:z.boolean().optional()}).strict();
export const statusConfigDtoSchema=z.object({id:identifierSchema,name:z.string(),description:z.string(),category:z.enum(['open','in_progress','waiting','blocked','in_review','completed','cancelled']),color:z.string(),textColor:z.string(),bgColor:z.string(),borderColor:z.string(),iconName:z.string(),order:z.number(),wipLimit:z.number().optional(),active:z.boolean(),allowedTeamIds:z.array(identifierSchema).optional(),isArchived:z.boolean().optional(),pausesSla:z.boolean().optional()}).strict();
export const statusCategorySchema=statusConfigDtoSchema.shape.category;
export const workflowPolicySchema=z.object({transitions:z.record(statusCategorySchema,z.array(statusCategorySchema)),requireCompletedChecklist:z.boolean(),requireCompletedDependencies:z.boolean(),overrideRoles:z.array(z.enum(['manager','module_admin'])),minimumOverrideJustificationLength:z.number().int().min(10).max(500)}).strict();
export const priorityConfigDtoSchema=z.object({id:identifierSchema,name:z.string(),level:z.number(),color:z.string(),bgColor:z.string(),textColor:z.string(),recommendedSlaDays:z.number(),iconName:z.string(),active:z.boolean()}).strict();
export const configurationKeySchema=z.enum(['categories','statuses','priorities','workflow']);
export const configurationsDtoSchema=z.object({categories:z.array(categoryConfigDtoSchema).optional(),statuses:z.array(statusConfigDtoSchema).optional(),priorities:z.array(priorityConfigDtoSchema).optional(),workflow:workflowPolicySchema.optional()}).strict();
export const configurationUpdateSchemas={categories:z.object({value:z.array(categoryConfigDtoSchema).max(200)}).strict(),statuses:z.object({value:z.array(statusConfigDtoSchema).max(200)}).strict(),priorities:z.object({value:z.array(priorityConfigDtoSchema).max(200)}).strict(),workflow:z.object({value:workflowPolicySchema}).strict()};
