import { z } from 'zod';
import type { Attachment, Demand } from '../types';
import { identifierSchema, optimisticVersionSchema, serializedDateSchema } from './common';

export const demandDateSchema = serializedDateSchema;
export const demandIdentitySchema = z.object({ id: identifierSchema, moduleId: identifierSchema, code: z.string().min(1).max(40), title: z.string().min(2).max(240), description: z.string().max(10000), categoryId: identifierSchema });
export const demandPlanningSchema = z.object({ createdAt: serializedDateSchema.optional(), plannedStartDate: serializedDateSchema.optional(), dueDate: serializedDateSchema.nullable().optional(), originalBaselineStartDate: serializedDateSchema.optional(), originalBaselineDueDate: serializedDateSchema.optional(), isMilestone: z.boolean().optional() });
export const demandAssignmentSchema = z.object({ requesterId: identifierSchema, assigneeId: z.string(), teamId: z.string(), clientId: z.string().nullable().optional(), clientName: z.string().optional(), participantIds: z.array(identifierSchema).optional() });
export const demandProgressSchema = z.object({ statusId: identifierSchema, priorityId: identifierSchema, progressPercent: z.number().min(0).max(100).optional(), completedAt: serializedDateSchema.optional(), completedByUserId: identifierSchema.optional(), completionSummary: z.string().optional(), updatedAt: serializedDateSchema.optional(), updatedByUserId: identifierSchema.optional() });
export const demandBlockerSchema = z.object({ isBlocked: z.boolean(), kind: z.enum(['blocker','impediment']).optional(), reason: z.string().optional(), impact: z.enum(['Baixo','Médio','Alto','Crítico']).optional(), blockedAt: serializedDateSchema.optional(), blockedByUserId: identifierSchema.optional(), actionNeeded: z.string().optional(), requiresBoardIntervention: z.boolean().optional(), resolvedAt: serializedDateSchema.optional(), createRelatedTask: z.boolean().optional(), responsibleTeamId: identifierSchema.optional(), linkedDemandId: identifierSchema.optional(), previousStatusId: identifierSchema.optional(), resolvedByDemandId: identifierSchema.optional() });
export const commentAttachmentSchema = z.object({ id:identifierSchema,name:z.string().min(1).max(255),size:z.number().int().nonnegative().max(2*1024*1024),type:z.string().min(1),url:z.string().min(1).max(3*1024*1024),uploadedByUserId:identifierSchema,uploadedAt:serializedDateSchema,isGoogleDrive:z.boolean().optional(),googleDriveId:z.string().optional(),sourceDevice:z.enum(['web','android']).optional() });
export const demandCommentSchema = z.object({ id:identifierSchema,userId:identifierSchema,userName:z.string(),userAvatar:z.string(),content:z.string(),createdAt:serializedDateSchema,editedAt:serializedDateSchema.optional(),editedByUserId:identifierSchema.optional(),mentions:z.array(identifierSchema).optional(),attachments:z.array(commentAttachmentSchema).optional(),isDecision:z.boolean().optional(),isConfidential:z.boolean().optional(),reactions:z.record(z.string(),z.array(identifierSchema)).optional(),readBy:z.array(z.object({userId:identifierSchema,readAt:serializedDateSchema})).optional() });
const checklistSchema=z.object({id:identifierSchema,title:z.string(),completed:z.boolean(),assignedToUserId:identifierSchema.optional(),dueDate:serializedDateSchema.optional(),completedAt:serializedDateSchema.optional()});
const financialSchema=z.object({estimatedCost:z.number(),approvedCost:z.number(),realizedCost:z.number(),estimatedHours:z.number(),realizedHours:z.number(),costCenter:z.string(),expectedBenefit:z.string(),realizedBenefit:z.string().optional(),financialImpact:z.string(),operationalImpact:z.string(),regulatoryImpact:z.string(),strategicImpact:z.string(),expectedReturnRoi:z.number().optional(),costVarianceJustification:z.string().optional()});
const slaSchema=z.object({policyId:z.string(),firstResponseDue:serializedDateSchema,firstResponseMetAt:serializedDateSchema.optional(),resolutionDue:serializedDateSchema,resolutionMetAt:serializedDateSchema.optional(),isBreached:z.boolean(),breachReason:z.string().optional(),isPaused:z.boolean(),totalPausedMinutes:z.number(),pauseHistory:z.array(z.object({pausedAt:serializedDateSchema,resumedAt:serializedDateSchema.optional(),reason:z.string(),statusId:identifierSchema,resumedByUserId:identifierSchema.optional()})),escalationLevel:z.enum(['none','manager','board'])});
const dependencySchema=z.object({id:identifierSchema,targetDemandId:identifierSchema,type:z.enum(['FS','SS','FF','SF']),lagDays:z.number()});

export const demandDtoSchema=demandIdentitySchema.merge(demandPlanningSchema).merge(demandAssignmentSchema).merge(demandProgressSchema).extend({version:optimisticVersionSchema,whyReason:z.string().optional(),expectedOutcome:z.string().optional(),whereLocation:z.string().optional(),howExecutionGuide:z.string().optional(),financials:financialSchema.optional(),sla:slaSchema.optional(),advancedDependencies:z.array(dependencySchema).optional(),dependencies:z.array(identifierSchema).optional(),tags:z.array(z.string()).optional(),checklist:z.array(checklistSchema).optional(),blocker:demandBlockerSchema.optional(),deadlineExtensions:z.array(z.object({id:identifierSchema,previousDueDate:serializedDateSchema,newDueDate:serializedDateSchema,reason:z.string(),approvedByUserId:identifierSchema,createdAt:serializedDateSchema})).optional(),attachments:z.array(commentAttachmentSchema).optional(),comments:z.array(demandCommentSchema).optional(),watchers:z.array(identifierSchema).optional(),isArchived:z.boolean().optional()});

const checklistInputSchema=checklistSchema.omit({completedAt:true}).strict();
const writableDemandFields=z.object({
  title:z.string().min(2).max(240),description:z.string().max(10000),statusId:identifierSchema,priorityId:identifierSchema,categoryId:identifierSchema,
  assigneeId:identifierSchema.nullable(),teamId:identifierSchema.nullable(),clientId:identifierSchema.nullable(),clientName:z.string().max(240),participantIds:z.array(identifierSchema).max(200),
  plannedStartDate:serializedDateSchema,dueDate:serializedDateSchema.nullable(),originalBaselineStartDate:serializedDateSchema,originalBaselineDueDate:serializedDateSchema,isMilestone:z.boolean(),
  whyReason:z.string().max(10000),expectedOutcome:z.string().max(10000),whereLocation:z.string().max(2000),howExecutionGuide:z.string().max(10000),
  financials:financialSchema,sla:slaSchema,advancedDependencies:z.array(dependencySchema).max(200),dependencies:z.array(identifierSchema).max(200),tags:z.array(z.string().max(100)).max(100),
  checklist:z.array(checklistInputSchema).max(500),progressPercent:z.number().int().min(0).max(100),watchers:z.array(identifierSchema).max(500)
}).strict();
export const demandCreateSchema=writableDemandFields.partial().extend({title:z.string().min(2).max(240),description:z.string().max(10000).default(''),statusId:identifierSchema,priorityId:identifierSchema,categoryId:identifierSchema}).strict();
export const workflowOverrideSchema=z.object({justification:z.string().trim().min(10).max(2000)}).strict();
export const demandUpdateSchema=writableDemandFields.partial().extend({version:optimisticVersionSchema,override:workflowOverrideSchema.optional()}).strict().superRefine((value,context)=>{
  if(value.statusId!==undefined&&(value.checklist!==undefined||value.dependencies!==undefined||value.advancedDependencies!==undefined))context.addIssue({code:'custom',path:['statusId'],message:'Altere checklist ou dependências antes de movimentar o status.'});
  if(value.progressPercent!==undefined&&value.checklist===undefined)context.addIssue({code:'custom',path:['progressPercent'],message:'O progresso somente pode ser alterado junto com o checklist.'});
  if(value.checklist!==undefined&&value.progressPercent!==undefined){const expected=value.checklist.length?Math.round(value.checklist.filter(item=>item.completed).length/value.checklist.length*100):0;if(value.progressPercent!==expected)context.addIssue({code:'custom',path:['progressPercent'],message:'O progresso deve corresponder aos itens concluídos do checklist.'});}
});
export const demandDeleteQuerySchema=z.object({version:z.coerce.number().int().positive()});
const queryIdList=z.preprocess(value=>typeof value==='string'?value.split(',').map(item=>item.trim()).filter(Boolean):value,z.array(identifierSchema).max(100).optional());
export const demandListQuerySchema=z.object({q:z.string().trim().max(200).optional(),statusId:identifierSchema.optional(),statusIds:queryIdList,priorityId:identifierSchema.optional(),priorityIds:queryIdList,categoryId:identifierSchema.optional(),categoryIds:queryIdList,assigneeId:identifierSchema.optional(),assigneeIds:queryIdList,teamId:identifierSchema.optional(),teamIds:queryIdList,clientId:identifierSchema.optional(),clientIds:queryIdList,sort:z.enum(['updatedAt','createdAt','dueDate','title','code']).default('updatedAt'),direction:z.enum(['asc','desc']).default('desc'),page:z.coerce.number().int().positive().default(1),pageSize:z.coerce.number().int().min(1).max(100).default(25)}).strict();
export const blockerInputSchema=z.object({version:optimisticVersionSchema,isBlocked:z.boolean(),kind:z.enum(['blocker','impediment']).default('blocker'),reason:z.string().max(2000).optional(),impact:z.enum(['Baixo','Médio','Alto','Crítico']).optional(),actionNeeded:z.string().max(2000).optional(),createRelatedTask:z.boolean().default(false),responsibleTeamId:identifierSchema.optional(),blockedStatusId:identifierSchema.optional(),initialStatusId:identifierSchema.optional(),taskCategoryId:identifierSchema.optional()}).strict().superRefine((v,c)=>{if(v.isBlocked&&!v.reason?.trim())c.addIssue({code:'custom',message:'O motivo do bloqueio é obrigatório.',path:['reason']});if(v.isBlocked&&v.createRelatedTask&&!v.responsibleTeamId)c.addIssue({code:'custom',message:'Selecione a equipe responsável.',path:['responsibleTeamId']});});
export const completeDemandInputSchema=z.object({statusId:identifierSchema,summary:z.string().min(1).max(5000),version:optimisticVersionSchema,override:workflowOverrideSchema.optional()}).strict();
export const addCommentInputSchema=z.object({version:optimisticVersionSchema,content:z.string().min(1).max(10000),attachments:z.array(commentAttachmentSchema.partial({uploadedByUserId:true,uploadedAt:true})).max(2).default([])}).strict();
export const editCommentInputSchema=z.object({version:optimisticVersionSchema,content:z.string().trim().min(1).max(10000)}).strict();
export const commentDtoSchema=demandCommentSchema;
export const commentMutationResponseSchema=z.object({comment:commentDtoSchema,demandVersion:optimisticVersionSchema}).strict();
export const blockerResponseSchema=z.object({demand:demandDtoSchema,createdDemand:demandDtoSchema.nullable().optional()});
export const completeDemandResponseSchema=z.object({demand:demandDtoSchema,autoUnblocked:z.array(demandDtoSchema).default([])});
export const demandListResponseSchema=z.object({items:z.array(demandDtoSchema),pagination:z.object({page:z.number().int().positive(),pageSize:z.number().int().positive(),total:z.number().int().nonnegative(),totalPages:z.number().int().nonnegative()})});

export type DemandDto=z.infer<typeof demandDtoSchema>;
export type CommentDto=z.infer<typeof commentDtoSchema>;
export type DemandCreateInput=z.input<typeof demandCreateSchema>;
export type DemandUpdateInput=z.input<typeof demandUpdateSchema>;
export type AddCommentInput={version:number;content:string;attachments?:Attachment[]};
export type BlockerInput=z.input<typeof blockerInputSchema>;
export type CompleteDemandInput=z.input<typeof completeDemandInputSchema>;
export type EditCommentInput=z.input<typeof editCommentInputSchema>;

const epoch=new Date(0).toISOString();
const attachmentDtoToDomain=(item:z.infer<typeof commentAttachmentSchema>):Attachment=>({...item,uploadedAt:item.uploadedAt??epoch});
const commentDtoToDomain=(item:CommentDto):Demand['comments'][number]=>({...item,createdAt:item.createdAt??epoch,attachments:item.attachments?.map(attachmentDtoToDomain),readBy:item.readBy?.map(read=>({...read,readAt:read.readAt??epoch}))});

export const demandDtoToDomain=(dto:DemandDto):Demand=>({
  ...dto, whyReason:dto.whyReason??'',expectedOutcome:dto.expectedOutcome??'',whereLocation:dto.whereLocation??'',howExecutionGuide:dto.howExecutionGuide??'',
  assigneeId:dto.assigneeId??'',teamId:dto.teamId??'',participantIds:dto.participantIds??[],createdAt:dto.createdAt??epoch,plannedStartDate:dto.plannedStartDate??dto.createdAt??epoch,dueDate:dto.dueDate??dto.createdAt??epoch,
  progressPercent:dto.progressPercent??0,financials:dto.financials??{estimatedCost:0,approvedCost:0,realizedCost:0,estimatedHours:0,realizedHours:0,costCenter:'',expectedBenefit:'',financialImpact:'',operationalImpact:'',regulatoryImpact:'',strategicImpact:''},
  sla:dto.sla?{...dto.sla,firstResponseDue:dto.sla.firstResponseDue??epoch,resolutionDue:dto.sla.resolutionDue??dto.dueDate??epoch,pauseHistory:dto.sla.pauseHistory.map(item=>({...item,pausedAt:item.pausedAt??epoch}))}:{policyId:'',firstResponseDue:dto.createdAt??epoch,resolutionDue:dto.dueDate??dto.createdAt??epoch,isBreached:false,isPaused:false,totalPausedMinutes:0,pauseHistory:[],escalationLevel:'none'},
  advancedDependencies:dto.advancedDependencies??[],dependencies:dto.dependencies??[],tags:dto.tags??[],checklist:dto.checklist??[],blocker:dto.blocker??{isBlocked:false},deadlineExtensions:(dto.deadlineExtensions??[]).map(item=>({...item,previousDueDate:item.previousDueDate??epoch,newDueDate:item.newDueDate??epoch,createdAt:item.createdAt??epoch})),attachments:(dto.attachments??[]).map(attachmentDtoToDomain),comments:(dto.comments??[]).map(commentDtoToDomain),watchers:dto.watchers??[],updatedAt:dto.updatedAt??dto.createdAt??epoch,updatedByUserId:dto.updatedByUserId??dto.requesterId
});
